---
all:
  children:
    proxmox_hosts:
      hosts:
        proxmox_bootstrap:
          ansible_connection: local
          ansible_host: localhost
    civic_cts:
      hosts:
        ingress1.diagnostics.kane-il.us:
          vmid: 102
          role_label: reverse_proxy_dns_secondary
          lan_ipv4: 192.168.1.102/16
          lan_ipv6: fd56:98f0:6a9::102/48
          public_ipv4: 15.235.0.200
          public_ipv6: 2607:5300:203:8784::102
          wireguard_ipv4: 10.0.0.102
          wireguard_ipv6: fd56:98f0:6a9:10::102/64
        ipfs1.diagnostics.kane-il.us:
          vmid: 106
          role_label: ipfs_git_posix_api
          lan_ipv4: 192.168.1.106/16
          lan_ipv6: fd56:98f0:6a9::106/48
          public_ipv4: 15.235.0.96
          public_ipv6: 2607:5300:203:8784::106
          wireguard_ipv4: 10.0.0.106
          wireguard_ipv6: fd56:98f0:6a9:10::106/64
        mail1.internal.diagnostics.kane-il.us:
          vmid: 107
          role_label: mail_backend
          lan_ipv4: 192.168.1.107/16
          lan_ipv6: fd56:98f0:6a9::107/48
        hubzilla1.internal.diagnostics.kane-il.us:
          vmid: 108
          role_label: hubzilla
          lan_ipv4: 192.168.1.108/16
          lan_ipv6: fd56:98f0:6a9::108/48
        orchestrator1.internal.diagnostics.kane-il.us:
          vmid: 109
          role_label: python_orchestration
          lan_ipv4: 192.168.1.109/16
          lan_ipv6: fd56:98f0:6a9::109/48
