<?php

function webforms_render_access_notice($mode) {
    if (webforms_access_state() === 'logged-in') {
        return '';
    }

    if ($mode === 'design') {
        return '
        <div class="alert alert-info py-2 webforms-access-notice" role="status">
            Public local-only Design mode. Sign in to save, publish, deploy, or use private services.
        </div>
        ';
    }

    return '
    <div class="alert alert-info py-2 webforms-access-notice" role="status">
        Public Deploy mode. Sign in to access private forms, storage, services, or federation.
    </div>
    ';
}

function webforms_render_design_page($design_form = '', $design_tab = '') {
    $forms = webforms_config_section('design_options');
    if (!array_key_exists($design_form, $forms)) {
        $design_form = '';
    }

    $design_tab = webforms_render_normalize_design_tab($design_tab);
    $label = webforms_h(webforms_config_label('design_options', $design_form, 'New blank form'));
    $description = webforms_h(webforms_config_label('design_descriptions', $design_form, ''));
    $access_state = webforms_access_state();

    return '
    <div id="webforms-runtime" class="webforms-content" data-webforms-mode="design" data-webforms-access="' . webforms_h($access_state) . '" data-webforms-design-form="' . webforms_h($design_form) . '" data-webforms-design-tab="' . webforms_h($design_tab) . '">
        <section id="webforms-design-workspace" class="webforms-design-workspace-placeholder" data-webforms-container="design-workspace">
            ' . webforms_render_access_notice('design') . '
            <h3>Design workspace: ' . $label . '</h3>
            <p>' . $description . '</p>
            ' . webforms_render_design_tab_nav($design_form, $design_tab) . '
            ' . webforms_render_design_tab_content($design_tab) . '
        </section>
    </div>
    ';
}

function webforms_render_normalize_design_tab($design_tab) {
    $tabs = webforms_config_section('design_tabs');
    if (!array_key_exists($design_tab, $tabs)) {
        return 'grid';
    }
    return $design_tab;
}

function webforms_render_design_tab_nav($design_form, $active_tab) {
    $tabs = webforms_config_section('design_tabs');
    $out = '<ul class="nav nav-tabs mb-3" id="webforms-design-tabs">';

    foreach ($tabs as $tab => $label) {
        $class = ($active_tab === $tab) ? 'nav-link active' : 'nav-link';
        $href = 'webforms?mode=design&design_form=' . rawurlencode($design_form) . '&design_tab=' . rawurlencode($tab);
        $out .= '<li class="nav-item">';
        $out .= '<a class="' . $class . '" href="' . webforms_h($href) . '">' . webforms_h($label) . '</a>';
        $out .= '</li>';
    }

    $out .= '</ul>';
    return $out;
}

function webforms_render_design_tab_content($design_tab) {
    if ($design_tab === 'json') {
        return webforms_render_design_json_tab();
    }

    if ($design_tab === 'help') {
        return webforms_render_design_help_tab();
    }

    return webforms_render_design_grid_tab();
}

function webforms_render_design_grid_tab() {
    return '
    <div id="webforms-design-grid-tab" data-webforms-design-tab-panel="grid">
        <div id="webforms-design-grid"
            class="webforms-design-grid"
            data-webforms-container="root-form"
            data-webforms-grid-size="24">
            <div id="webforms-grid-origin"
                class="webforms-grid-origin"
                data-webforms-grid-origin="0,0">
                root container · 24px grid · browser-local draft
            </div>
        </div>
    </div>
    ';
}

function webforms_render_design_json_tab() {
    return '
    <div id="webforms-design-json-tab" data-webforms-design-tab-panel="json">
        <h4>JSON</h4>
        <p>This tab shows the browser-local Webforms package generated by the Design workspace.</p>
        <textarea id="webforms-json-output" class="form-control" rows="18" readonly="readonly" data-webforms-json-output="package">Loading browser-local Webforms package JSON...</textarea>
    </div>
    ';
}

function webforms_render_design_help_tab() {
    return '
    <div id="webforms-design-help-tab" data-webforms-design-tab-panel="help">
        <h4>Help</h4>
        <p>Design mode creates inert JSON-composed webform definitions.</p>
        <ul>
            <li>Use Grid for visual placement.</li>
            <li>Use JSON to inspect, import, save, and reload the generated form definition.</li>
            <li>Deploy mode uses the Collection and Webform selectors to render deployment packages.</li>
            <li>Service execution, credentials, and federation behavior are not active.</li>
        </ul>
    </div>
    ';
}

function webforms_render_deploy_page($collection = '', $deploy_form = '') {
    $collections = webforms_config_section('collection_options');
    $forms = webforms_config_section('deploy_form_options');

    if (!array_key_exists($collection, $collections)) {
        $collection = '';
    }

    if (!array_key_exists($deploy_form, $forms)) {
        $deploy_form = '';
    }

    $collection_label = webforms_h(webforms_config_label('collection_display_labels', $collection, webforms_config_label('collection_options', $collection, 'No collection selected')));
    $form_label = webforms_h(webforms_config_label('deploy_form_display_labels', $deploy_form, webforms_config_label('deploy_form_options', $deploy_form, 'No webform selected')));
    $access_state = webforms_access_state();

    return '
    <div id="webforms-runtime" class="webforms-content" data-webforms-mode="deploy" data-webforms-access="' . webforms_h($access_state) . '" data-webforms-collection="' . webforms_h($collection) . '" data-webforms-deploy-form="' . webforms_h($deploy_form) . '">
        <section id="webforms-deploy-view" class="webforms-deploy-view-placeholder" data-webforms-container="deploy-view">
            ' . webforms_render_access_notice('deploy') . '
            <h3>Deploy preview</h3>
            <div id="webforms-deploy-render-root"
                class="webforms-deploy-render-root"
                data-webforms-deploy-render-root="1">
                <div id="webforms-deploy-empty-state" class="well" data-webforms-panel="empty-deploy-view">
                    <p><strong>Collection:</strong> ' . $collection_label . '</p>
                    <p><strong>Webform:</strong> ' . $form_label . '</p>
                    <p>Loading browser-local package renderer.</p>
                </div>
            </div>
        </section>
    </div>
    ';
}
